FROM python:3.10-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir requests

COPY entrypoint.py /entrypoint.py
COPY template_fasttechfood_prometheus.xml /template.xml

ENTRYPOINT ["python3", "/entrypoint.py"]
