version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  fasttechfoodapi:
    image: fast-tech-food-api
    container_name: fast-tech-food-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - EnableMetrics=true
      - DOTNET_ENABLE_METRICS=true
      - DOTNET_METRICS_ENDPOINT=http://*:5000/metrics
    stdin_open: true
    tty: true
    depends_on:
      - mongodb
    networks:
      - app-network
      - zabbix-net

  fasttechfoodapigateway:
    image: fast-tech-food-api-gateway
    container_name: fast-tech-food-api-gateway
    build:
      context: .
      dockerfile: Dockerfile.FastTechFood.API.Gateway
    restart: always
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5001
    depends_on:
      - mongodb
      - fasttechfoodapi
    networks:
      - app-network

  zabbix-db:
    image: mysql:8.0.32
    container_name: zabbix-db
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      MYSQL_ROOT_PASSWORD: root_pass
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --default-authentication-plugin=mysql_native_password
      - --max_allowed_packet=128M
      - --log_bin_trust_function_creators=1
    volumes:
      - zabbix_db_data:/var/lib/mysql
    networks:
      - zabbix-net

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-latest
    container_name: zabbix-server
    depends_on:
      - zabbix-db
    environment:
      DB_SERVER_HOST: zabbix-db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
    ports:
      - "10051:10051"
    volumes:
      - ./zabbix_server.conf:/etc/zabbix/zabbix_server.conf:ro
    networks:
      - zabbix-net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-latest
    container_name: zabbix-web
    depends_on:
      - zabbix-server
    environment:
      DB_SERVER_HOST: zabbix-db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: America/Sao_Paulo
    ports:
      - "8080:8080"
    networks:
      - zabbix-net

  zabbix-agent2:
    image: zabbix/zabbix-agent2:alpine-latest
    container_name: zabbix-agent2
    depends_on:
      - zabbix-server
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      ZBX_HOSTNAME: Zabbix_server
      ZBX_SERVER_ALLOWLIST: 127.0.0.1,zabbix-server,172.19.0.1,172.18.0.1
    volumes:
      - ./zabbix_agent2.conf:/etc/zabbix/zabbix_agent2.conf:ro
      - ./zabbix_agent2.d/:/etc/zabbix/zabbix_agent2.d/
      - ./scripts/:/etc/zabbix/scripts/:ro
    ports:
      - "10050:10050"
    networks:
      - zabbix-net


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - zabbix-net
      - app-network

  zabbix-template-importer:
    image: zabbix-template-importer
    container_name: zabbix-template-importer
    build:
      context: .
      dockerfile: Dockerfile.EntryPoint
    restart: "no"
    depends_on:
      - zabbix-web
    volumes:
      - ./template_fasttechfood_prometheus.xml:/template.xml:ro
      - ./entrypoint.py:/entrypoint.py:ro
    environment:
      ZABBIX_URL: http://zabbix-web:8080/api_jsonrpc.php
      ZABBIX_USER: Admin
      ZABBIX_PASS: zabbix
    command: ["python3", "/entrypoint.py"]
    networks:
      - zabbix-net

volumes:
  mongodb_data:
  zabbix_db_data:

networks:
  app-network:
  zabbix-net:
    driver: bridge
