global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'fasttechfoodapi'
    metrics_path: /metrics
    static_configs:
      - targets: ['fasttechfoodapi:5000']
    relabel_configs:
      - source_labels: ['__address__']
        target_label: 'instance'
        replacement: 'fasttechfoodapi:5000'
      - target_label: 'job'
        replacement: 'fasttechfoodapi'
