apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: fasttechfood
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus:9090
        access: proxy
        isDefault: true
        editable: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: fasttechfood
data:
  dashboard.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard
  namespace: fasttechfood
data:
  techchallenge.json: |
    {
      "title": "ASP.NET Core Metrics",
      "uid": "fast-tech-food-api-dashboard",
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "panels": [
        {
          "title": "Requests Duration",
          "type": "timeseries",
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "histogram_quantile(0.50, sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
              "legendFormat": "p50",
              "refId": "A"
            },
            {
              "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
              "legendFormat": "p95",
              "refId": "B"
            }
          ],
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          }
        }
      ],
      "templating": {
        "list": [
          {
            "name": "job",
            "type": "query",
            "datasource": "Prometheus",
            "query": "label_values(http_server_active_requests, job)",
            "refresh": 2
          },
          {
            "name": "instance",
            "type": "query",
            "datasource": "Prometheus",
            "query": "label_values(http_server_active_requests{job=~\"$job\"}, instance)",
            "refresh": 2
          }
        ]
      }
    }
