apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: fasttechfood
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'fasttechfood-api'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['fasttechfood-api:5000']