apiVersion: apps/v1
kind: Deployment
metadata:
  name: fasttechfood-api
  namespace: fasttechfood
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fasttechfood-api
  template:
    metadata:
      labels:
        app: fasttechfood-api
    spec:
      containers:
      - name: fasttechfood-api
        image: cabxavier/fiap-fasttechfood-api
        ports:
        - containerPort: 5000
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5000"
        - name: EnableMetrics
          value: "true"
        - name: DOTNET_ENABLE_METRICS
          value: "true"
        - name: DOTNET_METRICS_ENDPOINT
          value: "http://*:5000/metrics"
        - name: ConnectionStrings__MongoDBDocker
          value: "mongodb://mongodb:27017"
        - name: RabbitMQ__HostName
          value: "rabbitmq"
        - name: RabbitMQ__UserName
          value: "guest"
        - name: RabbitMQ__Password
          value: "guest"
        - name: RabbitMQ__Port
          value: "5672"
        - name: RabbitMQ__QueueCreateOrder
          value: "createorder"