apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: fasttechfood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
          - containerPort: 3000
          volumeMounts:
          - name: config-volume
            mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
            subPath: datasource.yaml
          - name: dashboards-volume
            mountPath: /etc/grafana/provisioning/dashboards/dashboard.yaml
            subPath: dashboard.yaml
          - name: dashboard-volume
            mountPath: /var/lib/grafana/dashboards/techchallenge.json
            subPath: techchallenge.json
      volumes:
      - name: config-volume
        configMap:
          name: grafana-datasource
      - name: dashboards-volume
        configMap:
          name: grafana-dashboards
      - name: dashboard-volume
        configMap:
          name: grafana-dashboard