apiVersion: v1
kind: Service
metadata:
  name: fasttechfood-api
  namespace: fasttechfood
spec:
  selector:
    app: fasttechfood-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30416
  type: NodePort