apiVersion: v1
kind: Service
metadata:
  name: fasttechfood-api-gateway
  namespace: fasttechfood
spec:
  selector:
    app: fasttechfood-api-gateway
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30165
  type: NodePort