apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: fasttechfood
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30722
  type: NodePort