apiVersion: v1
kind: Service
metadata:
  name: zabbix-agent2
  namespace: fasttechfood
spec:
  selector:
    app: zabbix-agent2
  ports:
    - protocol: TCP
      port: 10050
      targetPort: 10050
  type: NodePort