apiVersion: v1
kind: Service
metadata:
  name: zabbix-db
  namespace: fasttechfood
spec:
  selector:
    app: zabbix-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: NodePort