apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  namespace: fasttechfood
spec:
  selector:
    app: zabbix-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort